// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/languages.json. DO NOT EDIT.
// It lists the shipping languages; make i18n DRAFT=1 adds the drafts and the pseudo-locale.

/// A language this build of the app can show its own text in.
struct L10nLanguage: Sendable, Hashable, Identifiable {
    /// The code stored on the device and sent in every request ("pt").
    let code: String
    /// The BCP 47 tag that picks plural rules and number formats ("pt-PT").
    let tag: String
    /// The .lproj folder its compiled tables are in ("pt-PT").
    let apple: String
    /// The language's own name, for the picker ("Português").
    let name: String
    /// The pseudo-locale of draft builds, never matched to the system language.
    let pseudo: Bool

    var id: String { code }
}

extension L10nLanguage {
    /// Every language of this build, in the picker's order, English first.
    static let all: [L10nLanguage] = [
        L10nLanguage(code: "en", tag: "en", apple: "en", name: "English", pseudo: false),
    ]

    /// English: the source text, and the fallback for anything missing.
    static let english = all[0]
}
