// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/strings/en/common.json. DO NOT EDIT.
// Change the text there and run make i18n (i18n/README.md); the strings are in Common.xcstrings.

import Foundation

extension S {
    /// Accept
    ///
    /// Button that accepts a friend request.
    static var commonAccept: String { L("common.accept", table: "Common") }

    /// Add
    ///
    /// Button that adds what was typed in a form (for example a new user).
    static var commonAdd: String { L("common.add", table: "Common") }

    /// Apply
    ///
    /// Button that applies a change, such as trimming a video.
    static var commonApply: String { L("common.apply", table: "Common") }

    /// Back
    ///
    /// Button that returns to the previous step of a wizard or dialog.
    static var commonBack: String { L("common.back", table: "Common") }

    /// Cancel
    ///
    /// Button that closes a dialog or stops an action without changing anything. Every app.
    static var commonCancel: String { L("common.cancel", table: "Common") }

    /// Choose
    ///
    /// Button in a folder picker that picks the folder being looked at.
    static var commonChoose: String { L("common.choose", table: "Common") }

    /// Close
    ///
    /// Button or icon label that closes a panel, viewer or dialog.
    static var commonClose: String { L("common.close", table: "Common") }

    /// Connect
    ///
    /// Button that connects to the device or to a Wi-Fi network.
    static var commonConnect: String { L("common.connect", table: "Common") }

    /// Connecting…
    ///
    /// Shown while connecting to the device or a Wi-Fi network.
    static var commonConnecting: String { L("common.connecting", table: "Common") }

    /// Create
    ///
    /// Button that creates a new collection from the selected photos.
    static var commonCreate: String { L("common.create", table: "Common") }

    /// Decline
    ///
    /// Button that turns down a friend request.
    static var commonDecline: String { L("common.decline", table: "Common") }

    /// Delete
    ///
    /// Button or menu item that deletes the selected photos, files, users or links, usually after a confirmation.
    static var commonDelete: String { L("common.delete", table: "Common") }

    /// Deleting…
    ///
    /// Shown on the Delete button while the deletion runs.
    static var commonDeleting: String { L("common.deleting", table: "Common") }

    /// Deselect
    ///
    /// Accessibility action that takes one photo or file out of the selection.
    static var commonDeselect: String { L("common.deselect", table: "Common") }

    /// Disconnect
    ///
    /// Button in the computer apps that disconnects from the device (after a confirmation).
    static var commonDisconnect: String { L("common.disconnect", table: "Common") }

    /// Done
    ///
    /// Button that finishes a task or leaves an editing screen, keeping what was done.
    static var commonDone: String { L("common.done", table: "Common") }

    /// Download
    ///
    /// Button that downloads a file or a ZIP to this computer or phone.
    static var commonDownload: String { L("common.download", table: "Common") }

    /// Loading…
    ///
    /// Shown while a list or a picture is loading.
    static var commonLoading: String { L("common.loading", table: "Common") }

    /// Next
    ///
    /// Button that goes to the next step of a wizard or dialog.
    static var commonNext: String { L("common.next", table: "Common") }

    /// OK
    ///
    /// Button that closes a message after reading it. Use the platform's usual word.
    static var commonOk: String { L("common.ok", table: "Common") }

    /// Open
    ///
    /// Button that opens a shared link or a folder.
    static var commonOpen: String { L("common.open", table: "Common") }

    /// Password
    ///
    /// Label of a password field (the device's password, an account's, or a Wi-Fi network's).
    static var commonPassword: String { L("common.password", table: "Common") }

    /// Pause
    ///
    /// Button that pauses uploads or the live log view.
    static var commonPause: String { L("common.pause", table: "Common") }

    /// Quit
    ///
    /// Menu item that quits the computer app.
    static var commonQuit: String { L("common.quit", table: "Common") }

    /// Refresh
    ///
    /// Button that reloads a list (friends, files).
    static var commonRefresh: String { L("common.refresh", table: "Common") }

    /// Remove
    ///
    /// Button that takes an item out of a list or a selection without deleting the file itself.
    static var commonRemove: String { L("common.remove", table: "Common") }

    /// Rename
    ///
    /// Button or menu item that gives a person, collection or file a new name.
    static var commonRename: String { L("common.rename", table: "Common") }

    /// Resume
    ///
    /// Button that continues what Pause stopped.
    static var commonResume: String { L("common.resume", table: "Common") }

    /// Save
    ///
    /// Button that stores a change (a new name, a setting).
    static var commonSave: String { L("common.save", table: "Common") }

    /// Search
    ///
    /// Button that runs a search, or the search field's short placeholder.
    static var commonSearch: String { L("common.search", table: "Common") }

    /// Select
    ///
    /// Button or accessibility action that starts selecting, or selects one photo or file.
    static var commonSelect: String { L("common.select", table: "Common") }

    /// Send
    ///
    /// Button that sends something: a friend request, the device's logs.
    static var commonSend: String { L("common.send", table: "Common") }

    /// Settings
    ///
    /// The Settings section or screen, in menus and titles.
    static var commonSettings: String { L("common.settings", table: "Common") }

    /// Share
    ///
    /// Button or menu item that shares photos or files (opens the share options).
    static var commonShare: String { L("common.share", table: "Common") }

    /// Try again
    ///
    /// Button shown after something failed, to repeat it.
    static var commonTryAgain: String { L("common.try_again", table: "Common") }

    /// Update
    ///
    /// Button on the update banner that opens the device's software update. A verb.
    static var commonUpdate: String { L("common.update", table: "Common") }

    /// Updating…
    ///
    /// Shown while the device installs a software update.
    static var commonUpdating: String { L("common.updating", table: "Common") }

    /// Upload
    ///
    /// Button that sends the selected items from this phone to the device.
    static var commonUpload: String { L("common.upload", table: "Common") }
}
