// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/languages.json. DO NOT EDIT.
// Change the catalog and run make i18n (i18n/README.md).

package cloud.offthe.otc.i18n

/** A language the app's generated resources hold (i18n/languages.json). */
data class Language(
    /** Stored, sent on the wire and used in file names ("pt"). */
    val code: String,
    /**
     * The BCP 47 tag behind plural rules and number formats ("pt-PT"), and the
     * locale to hand Android (setApplicationLocales or a configuration):
     * values-<qualifier> holds its resources. Always this tag, never the bare
     * code: "pt" would pick Brazilian plural rules from the same values-pt.
     */
    val tag: String,
    /** The language's own name, for the picker. */
    val name: String,
)

/**
 * The languages of this build, English first: the shipping ones, and in a
 * make i18n DRAFT=1 build (never committed) the drafts and the pseudo-locale.
 */
object Languages {
    /** English: the source, and the text of anything not translated. */
    const val SOURCE: String = "en"

    val all: List<Language> = listOf(
        Language(code = "en", tag = "en", name = "English"),
    )

    /** The language with this code, or null. */
    fun forCode(code: String): Language? = all.firstOrNull { it.code == code }
}
