// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/strings/en/android.json. DO NOT EDIT.
// Change the catalog and run make i18n (i18n/README.md).

package cloud.offthe.otc.i18n

import cloud.offthe.otc.R

/** "Friends and posts": Name of the notification channel for pushes, shown in Android's notification settings for the app. */
fun S.androidNotificationChannel(): UiText =
    UiText.Res(R.string.android_notification_channel)

/** "Friend requests, new posts, likes and comments": Description of that notification channel, shown under its name in Android's notification settings. */
fun S.androidNotificationChannelDescription(): UiText =
    UiText.Res(R.string.android_notification_channel_description)
