// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/strings/en/app.settings.json. DO NOT EDIT.
// Change the catalog and run make i18n (i18n/README.md).

package cloud.offthe.otc.i18n

import cloud.offthe.otc.R

/** "Language": Row in Settings that opens the Language screen, and that screen's title. */
fun S.appSettingsLanguage(): UiText =
    UiText.Res(R.string.app_settings_language)

/** "Automatic": Value of the Language row in Settings when no language is chosen: the app follows the language the phone is set to. */
fun S.appSettingsLanguageAutomatic(): UiText =
    UiText.Res(R.string.app_settings_language_automatic)

/** "Automatic ({language})": First choice on the Language screen: follow the language the phone is set to. {language} is the language that gives, written in that language (Español, Deutsch). */
fun S.appSettingsLanguageAutomaticNamed(language: String): UiText =
    UiText.Res(R.string.app_settings_language_automatic_named, listOf(language))

/** "Saved on your device, so every app signed in to it uses the same language. Automatic follows the language this phone is set to.": Explanation under the list of languages on the Language screen. */
fun S.appSettingsLanguageFooter(): UiText =
    UiText.Res(R.string.app_settings_language_footer)

/** "Your device needs a software update to share this choice with your other apps. Until then it applies to this phone only.": Shown under the list of languages on the Language screen when the device's software is too old to keep the language. */
fun S.appSettingsLanguageThisPhone(): UiText =
    UiText.Res(R.string.app_settings_language_this_phone)
