// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/strings/en/common.json. DO NOT EDIT.
// Change the catalog and run make i18n (i18n/README.md).

package cloud.offthe.otc.i18n

import cloud.offthe.otc.R

/** "Accept": Button that accepts a friend request. */
fun S.commonAccept(): UiText =
    UiText.Res(R.string.common_accept)

/** "Add": Button that adds what was typed in a form (for example a new user). */
fun S.commonAdd(): UiText =
    UiText.Res(R.string.common_add)

/** "Apply": Button that applies a change, such as trimming a video. */
fun S.commonApply(): UiText =
    UiText.Res(R.string.common_apply)

/** "Back": Button that returns to the previous step of a wizard or dialog. */
fun S.commonBack(): UiText =
    UiText.Res(R.string.common_back)

/** "Cancel": Button that closes a dialog or stops an action without changing anything. Every app. */
fun S.commonCancel(): UiText =
    UiText.Res(R.string.common_cancel)

/** "Choose": Button in a folder picker that picks the folder being looked at. */
fun S.commonChoose(): UiText =
    UiText.Res(R.string.common_choose)

/** "Close": Button or icon label that closes a panel, viewer or dialog. */
fun S.commonClose(): UiText =
    UiText.Res(R.string.common_close)

/** "Connect": Button that connects to the device or to a Wi-Fi network. */
fun S.commonConnect(): UiText =
    UiText.Res(R.string.common_connect)

/** "Connecting…": Shown while connecting to the device or a Wi-Fi network. */
fun S.commonConnecting(): UiText =
    UiText.Res(R.string.common_connecting)

/** "Create": Button that creates a new collection from the selected photos. */
fun S.commonCreate(): UiText =
    UiText.Res(R.string.common_create)

/** "Decline": Button that turns down a friend request. */
fun S.commonDecline(): UiText =
    UiText.Res(R.string.common_decline)

/** "Delete": Button or menu item that deletes the selected photos, files, users or links, usually after a confirmation. */
fun S.commonDelete(): UiText =
    UiText.Res(R.string.common_delete)

/** "Deleting…": Shown on the Delete button while the deletion runs. */
fun S.commonDeleting(): UiText =
    UiText.Res(R.string.common_deleting)

/** "Deselect": Accessibility action that takes one photo or file out of the selection. */
fun S.commonDeselect(): UiText =
    UiText.Res(R.string.common_deselect)

/** "Disconnect": Button in the computer apps that disconnects from the device (after a confirmation). */
fun S.commonDisconnect(): UiText =
    UiText.Res(R.string.common_disconnect)

/** "Done": Button that finishes a task or leaves an editing screen, keeping what was done. */
fun S.commonDone(): UiText =
    UiText.Res(R.string.common_done)

/** "Download": Button that downloads a file or a ZIP to this computer or phone. */
fun S.commonDownload(): UiText =
    UiText.Res(R.string.common_download)

/** "Loading…": Shown while a list or a picture is loading. */
fun S.commonLoading(): UiText =
    UiText.Res(R.string.common_loading)

/** "Next": Button that goes to the next step of a wizard or dialog. */
fun S.commonNext(): UiText =
    UiText.Res(R.string.common_next)

/** "OK": Button that closes a message after reading it. Use the platform's usual word. */
fun S.commonOk(): UiText =
    UiText.Res(R.string.common_ok)

/** "Open": Button that opens a shared link or a folder. */
fun S.commonOpen(): UiText =
    UiText.Res(R.string.common_open)

/** "Password": Label of a password field (the device's password, an account's, or a Wi-Fi network's). */
fun S.commonPassword(): UiText =
    UiText.Res(R.string.common_password)

/** "Pause": Button that pauses uploads or the live log view. */
fun S.commonPause(): UiText =
    UiText.Res(R.string.common_pause)

/** "Quit": Menu item that quits the computer app. */
fun S.commonQuit(): UiText =
    UiText.Res(R.string.common_quit)

/** "Refresh": Button that reloads a list (friends, files). */
fun S.commonRefresh(): UiText =
    UiText.Res(R.string.common_refresh)

/** "Remove": Button that takes an item out of a list or a selection without deleting the file itself. */
fun S.commonRemove(): UiText =
    UiText.Res(R.string.common_remove)

/** "Rename": Button or menu item that gives a person, collection or file a new name. */
fun S.commonRename(): UiText =
    UiText.Res(R.string.common_rename)

/** "Resume": Button that continues what Pause stopped. */
fun S.commonResume(): UiText =
    UiText.Res(R.string.common_resume)

/** "Save": Button that stores a change (a new name, a setting). */
fun S.commonSave(): UiText =
    UiText.Res(R.string.common_save)

/** "Search": Button that runs a search, or the search field's short placeholder. */
fun S.commonSearch(): UiText =
    UiText.Res(R.string.common_search)

/** "Select": Button or accessibility action that starts selecting, or selects one photo or file. */
fun S.commonSelect(): UiText =
    UiText.Res(R.string.common_select)

/** "Send": Button that sends something: a friend request, the device's logs. */
fun S.commonSend(): UiText =
    UiText.Res(R.string.common_send)

/** "Settings": The Settings section or screen, in menus and titles. */
fun S.commonSettings(): UiText =
    UiText.Res(R.string.common_settings)

/** "Share": Button or menu item that shares photos or files (opens the share options). */
fun S.commonShare(): UiText =
    UiText.Res(R.string.common_share)

/** "Try again": Button shown after something failed, to repeat it. */
fun S.commonTryAgain(): UiText =
    UiText.Res(R.string.common_try_again)

/** "Update": Button on the update banner that opens the device's software update. A verb. */
fun S.commonUpdate(): UiText =
    UiText.Res(R.string.common_update)

/** "Updating…": Shown while the device installs a software update. */
fun S.commonUpdating(): UiText =
    UiText.Res(R.string.common_updating)

/** "Upload": Button that sends the selected items from this phone to the device. */
fun S.commonUpload(): UiText =
    UiText.Res(R.string.common_upload)
