// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "msg";

export const ErrorCode = { Unknown: 0, UNRECOGNIZED: -1 } as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

export namespace ErrorCode {
  export type Unknown = typeof ErrorCode.Unknown;
  export type UNRECOGNIZED = typeof ErrorCode.UNRECOGNIZED;
}

export function errorCodeFromJSON(object: any): ErrorCode {
  switch (object) {
    case 0:
    case "Unknown":
      return ErrorCode.Unknown;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ErrorCode.UNRECOGNIZED;
  }
}

export function errorCodeToJSON(object: ErrorCode): string {
  switch (object) {
    case ErrorCode.Unknown:
      return "Unknown";
    case ErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GetStatus {
}

export interface Status {
  online: boolean;
  localIp: number;
  nasStatus: number;
  disks: number;
  errorCodes: ErrorCode[];
}

export interface Auth {
  uuid: string;
  key: string;
  create: boolean;
}

export interface UploadFile {
  path: string;
  content: Uint8Array;
  forceOverride: boolean;
}

export interface DelFile {
  path: string;
}

export interface GetFile {
  path: string;
}

export interface ListFiles {
  globbing: boolean;
  path: string;
}

export interface ListOfFiles {
  files: File[];
}

export interface FileTag {
  tag: string;
  type: string;
}

export interface File {
  hash: string;
  mime: string;
  created?: Date | undefined;
  modified?: Date | undefined;
  path: string;
  size: number;
  tags: FileTag[];
  content?: Uint8Array | undefined;
}

export interface Ack {
  ok: boolean;
  errorMsg: string;
}

export interface ReqEnvelope {
  id: number;
  payload?:
    | { $case: "reqListFiles"; reqListFiles: ListFiles }
    | { $case: "reqGetStatus"; reqGetStatus: GetStatus }
    | { $case: "reqAuth"; reqAuth: Auth }
    | { $case: "reqUploadFile"; reqUploadFile: UploadFile }
    | { $case: "reqGetFile"; reqGetFile: GetFile }
    | { $case: "reqDelFile"; reqDelFile: DelFile }
    | undefined;
}

export interface RespEnvelope {
  id: number;
  error: boolean;
  errorMessage: string;
  payload?:
    | { $case: "respStatus"; respStatus: Status }
    | { $case: "respAck"; respAck: Ack }
    | { $case: "respFile"; respFile: File }
    | { $case: "respListOfFiles"; respListOfFiles: ListOfFiles }
    | undefined;
}

function createBaseGetStatus(): GetStatus {
  return {};
}

export const GetStatus: MessageFns<GetStatus> = {
  encode(_: GetStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetStatus {
    return {};
  },

  toJSON(_: GetStatus): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStatus>, I>>(base?: I): GetStatus {
    return GetStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStatus>, I>>(_: I): GetStatus {
    const message = createBaseGetStatus();
    return message;
  },
};

function createBaseStatus(): Status {
  return { online: false, localIp: 0, nasStatus: 0, disks: 0, errorCodes: [] };
}

export const Status: MessageFns<Status> = {
  encode(message: Status, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.online !== false) {
      writer.uint32(8).bool(message.online);
    }
    if (message.localIp !== 0) {
      writer.uint32(16).int32(message.localIp);
    }
    if (message.nasStatus !== 0) {
      writer.uint32(24).int32(message.nasStatus);
    }
    if (message.disks !== 0) {
      writer.uint32(32).int32(message.disks);
    }
    writer.uint32(42).fork();
    for (const v of message.errorCodes) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Status {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.online = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.localIp = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.nasStatus = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.disks = reader.int32();
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.errorCodes.push(reader.int32() as any);

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.errorCodes.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Status {
    return {
      online: isSet(object.online) ? globalThis.Boolean(object.online) : false,
      localIp: isSet(object.localIp) ? globalThis.Number(object.localIp) : 0,
      nasStatus: isSet(object.nasStatus) ? globalThis.Number(object.nasStatus) : 0,
      disks: isSet(object.disks) ? globalThis.Number(object.disks) : 0,
      errorCodes: globalThis.Array.isArray(object?.errorCodes)
        ? object.errorCodes.map((e: any) => errorCodeFromJSON(e))
        : [],
    };
  },

  toJSON(message: Status): unknown {
    const obj: any = {};
    if (message.online !== false) {
      obj.online = message.online;
    }
    if (message.localIp !== 0) {
      obj.localIp = Math.round(message.localIp);
    }
    if (message.nasStatus !== 0) {
      obj.nasStatus = Math.round(message.nasStatus);
    }
    if (message.disks !== 0) {
      obj.disks = Math.round(message.disks);
    }
    if (message.errorCodes?.length) {
      obj.errorCodes = message.errorCodes.map((e) => errorCodeToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Status>, I>>(base?: I): Status {
    return Status.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Status>, I>>(object: I): Status {
    const message = createBaseStatus();
    message.online = object.online ?? false;
    message.localIp = object.localIp ?? 0;
    message.nasStatus = object.nasStatus ?? 0;
    message.disks = object.disks ?? 0;
    message.errorCodes = object.errorCodes?.map((e) => e) || [];
    return message;
  },
};

function createBaseAuth(): Auth {
  return { uuid: "", key: "", create: false };
}

export const Auth: MessageFns<Auth> = {
  encode(message: Auth, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.create !== false) {
      writer.uint32(24).bool(message.create);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Auth {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuth();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.create = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Auth {
    return {
      uuid: isSet(object.uuid) ? globalThis.String(object.uuid) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      create: isSet(object.create) ? globalThis.Boolean(object.create) : false,
    };
  },

  toJSON(message: Auth): unknown {
    const obj: any = {};
    if (message.uuid !== "") {
      obj.uuid = message.uuid;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.create !== false) {
      obj.create = message.create;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Auth>, I>>(base?: I): Auth {
    return Auth.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Auth>, I>>(object: I): Auth {
    const message = createBaseAuth();
    message.uuid = object.uuid ?? "";
    message.key = object.key ?? "";
    message.create = object.create ?? false;
    return message;
  },
};

function createBaseUploadFile(): UploadFile {
  return { path: "", content: new Uint8Array(0), forceOverride: false };
}

export const UploadFile: MessageFns<UploadFile> = {
  encode(message: UploadFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.content.length !== 0) {
      writer.uint32(18).bytes(message.content);
    }
    if (message.forceOverride !== false) {
      writer.uint32(24).bool(message.forceOverride);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.forceOverride = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadFile {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      content: isSet(object.content) ? bytesFromBase64(object.content) : new Uint8Array(0),
      forceOverride: isSet(object.forceOverride) ? globalThis.Boolean(object.forceOverride) : false,
    };
  },

  toJSON(message: UploadFile): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.content.length !== 0) {
      obj.content = base64FromBytes(message.content);
    }
    if (message.forceOverride !== false) {
      obj.forceOverride = message.forceOverride;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadFile>, I>>(base?: I): UploadFile {
    return UploadFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadFile>, I>>(object: I): UploadFile {
    const message = createBaseUploadFile();
    message.path = object.path ?? "";
    message.content = object.content ?? new Uint8Array(0);
    message.forceOverride = object.forceOverride ?? false;
    return message;
  },
};

function createBaseDelFile(): DelFile {
  return { path: "" };
}

export const DelFile: MessageFns<DelFile> = {
  encode(message: DelFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DelFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDelFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DelFile {
    return { path: isSet(object.path) ? globalThis.String(object.path) : "" };
  },

  toJSON(message: DelFile): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DelFile>, I>>(base?: I): DelFile {
    return DelFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DelFile>, I>>(object: I): DelFile {
    const message = createBaseDelFile();
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseGetFile(): GetFile {
  return { path: "" };
}

export const GetFile: MessageFns<GetFile> = {
  encode(message: GetFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFile {
    return { path: isSet(object.path) ? globalThis.String(object.path) : "" };
  },

  toJSON(message: GetFile): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetFile>, I>>(base?: I): GetFile {
    return GetFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetFile>, I>>(object: I): GetFile {
    const message = createBaseGetFile();
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseListFiles(): ListFiles {
  return { globbing: false, path: "" };
}

export const ListFiles: MessageFns<ListFiles> = {
  encode(message: ListFiles, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.globbing !== false) {
      writer.uint32(8).bool(message.globbing);
    }
    if (message.path !== "") {
      writer.uint32(18).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFiles {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFiles();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.globbing = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListFiles {
    return {
      globbing: isSet(object.globbing) ? globalThis.Boolean(object.globbing) : false,
      path: isSet(object.path) ? globalThis.String(object.path) : "",
    };
  },

  toJSON(message: ListFiles): unknown {
    const obj: any = {};
    if (message.globbing !== false) {
      obj.globbing = message.globbing;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListFiles>, I>>(base?: I): ListFiles {
    return ListFiles.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListFiles>, I>>(object: I): ListFiles {
    const message = createBaseListFiles();
    message.globbing = object.globbing ?? false;
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseListOfFiles(): ListOfFiles {
  return { files: [] };
}

export const ListOfFiles: MessageFns<ListOfFiles> = {
  encode(message: ListOfFiles, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.files) {
      File.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListOfFiles {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListOfFiles();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.files.push(File.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListOfFiles {
    return { files: globalThis.Array.isArray(object?.files) ? object.files.map((e: any) => File.fromJSON(e)) : [] };
  },

  toJSON(message: ListOfFiles): unknown {
    const obj: any = {};
    if (message.files?.length) {
      obj.files = message.files.map((e) => File.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListOfFiles>, I>>(base?: I): ListOfFiles {
    return ListOfFiles.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListOfFiles>, I>>(object: I): ListOfFiles {
    const message = createBaseListOfFiles();
    message.files = object.files?.map((e) => File.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFileTag(): FileTag {
  return { tag: "", type: "" };
}

export const FileTag: MessageFns<FileTag> = {
  encode(message: FileTag, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tag !== "") {
      writer.uint32(10).string(message.tag);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileTag {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileTag();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tag = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileTag {
    return {
      tag: isSet(object.tag) ? globalThis.String(object.tag) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
    };
  },

  toJSON(message: FileTag): unknown {
    const obj: any = {};
    if (message.tag !== "") {
      obj.tag = message.tag;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileTag>, I>>(base?: I): FileTag {
    return FileTag.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileTag>, I>>(object: I): FileTag {
    const message = createBaseFileTag();
    message.tag = object.tag ?? "";
    message.type = object.type ?? "";
    return message;
  },
};

function createBaseFile(): File {
  return {
    hash: "",
    mime: "",
    created: undefined,
    modified: undefined,
    path: "",
    size: 0,
    tags: [],
    content: undefined,
  };
}

export const File: MessageFns<File> = {
  encode(message: File, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hash !== "") {
      writer.uint32(10).string(message.hash);
    }
    if (message.mime !== "") {
      writer.uint32(18).string(message.mime);
    }
    if (message.created !== undefined) {
      Timestamp.encode(toTimestamp(message.created), writer.uint32(26).fork()).join();
    }
    if (message.modified !== undefined) {
      Timestamp.encode(toTimestamp(message.modified), writer.uint32(34).fork()).join();
    }
    if (message.path !== "") {
      writer.uint32(42).string(message.path);
    }
    if (message.size !== 0) {
      writer.uint32(48).int32(message.size);
    }
    for (const v of message.tags) {
      FileTag.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.content !== undefined) {
      writer.uint32(66).bytes(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): File {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mime = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.created = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.modified = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tags.push(FileTag.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.content = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): File {
    return {
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
      mime: isSet(object.mime) ? globalThis.String(object.mime) : "",
      created: isSet(object.created) ? fromJsonTimestamp(object.created) : undefined,
      modified: isSet(object.modified) ? fromJsonTimestamp(object.modified) : undefined,
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => FileTag.fromJSON(e)) : [],
      content: isSet(object.content) ? bytesFromBase64(object.content) : undefined,
    };
  },

  toJSON(message: File): unknown {
    const obj: any = {};
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    if (message.mime !== "") {
      obj.mime = message.mime;
    }
    if (message.created !== undefined) {
      obj.created = message.created.toISOString();
    }
    if (message.modified !== undefined) {
      obj.modified = message.modified.toISOString();
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.tags?.length) {
      obj.tags = message.tags.map((e) => FileTag.toJSON(e));
    }
    if (message.content !== undefined) {
      obj.content = base64FromBytes(message.content);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<File>, I>>(base?: I): File {
    return File.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<File>, I>>(object: I): File {
    const message = createBaseFile();
    message.hash = object.hash ?? "";
    message.mime = object.mime ?? "";
    message.created = object.created ?? undefined;
    message.modified = object.modified ?? undefined;
    message.path = object.path ?? "";
    message.size = object.size ?? 0;
    message.tags = object.tags?.map((e) => FileTag.fromPartial(e)) || [];
    message.content = object.content ?? undefined;
    return message;
  },
};

function createBaseAck(): Ack {
  return { ok: false, errorMsg: "" };
}

export const Ack: MessageFns<Ack> = {
  encode(message: Ack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.errorMsg !== "") {
      writer.uint32(18).string(message.errorMsg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorMsg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ack {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      errorMsg: isSet(object.errorMsg) ? globalThis.String(object.errorMsg) : "",
    };
  },

  toJSON(message: Ack): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.errorMsg !== "") {
      obj.errorMsg = message.errorMsg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ack>, I>>(base?: I): Ack {
    return Ack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ack>, I>>(object: I): Ack {
    const message = createBaseAck();
    message.ok = object.ok ?? false;
    message.errorMsg = object.errorMsg ?? "";
    return message;
  },
};

function createBaseReqEnvelope(): ReqEnvelope {
  return { id: 0, payload: undefined };
}

export const ReqEnvelope: MessageFns<ReqEnvelope> = {
  encode(message: ReqEnvelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    switch (message.payload?.$case) {
      case "reqListFiles":
        ListFiles.encode(message.payload.reqListFiles, writer.uint32(82).fork()).join();
        break;
      case "reqGetStatus":
        GetStatus.encode(message.payload.reqGetStatus, writer.uint32(90).fork()).join();
        break;
      case "reqAuth":
        Auth.encode(message.payload.reqAuth, writer.uint32(98).fork()).join();
        break;
      case "reqUploadFile":
        UploadFile.encode(message.payload.reqUploadFile, writer.uint32(106).fork()).join();
        break;
      case "reqGetFile":
        GetFile.encode(message.payload.reqGetFile, writer.uint32(114).fork()).join();
        break;
      case "reqDelFile":
        DelFile.encode(message.payload.reqDelFile, writer.uint32(122).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReqEnvelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReqEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.payload = { $case: "reqListFiles", reqListFiles: ListFiles.decode(reader, reader.uint32()) };
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.payload = { $case: "reqGetStatus", reqGetStatus: GetStatus.decode(reader, reader.uint32()) };
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.payload = { $case: "reqAuth", reqAuth: Auth.decode(reader, reader.uint32()) };
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.payload = { $case: "reqUploadFile", reqUploadFile: UploadFile.decode(reader, reader.uint32()) };
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.payload = { $case: "reqGetFile", reqGetFile: GetFile.decode(reader, reader.uint32()) };
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.payload = { $case: "reqDelFile", reqDelFile: DelFile.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReqEnvelope {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      payload: isSet(object.reqListFiles)
        ? { $case: "reqListFiles", reqListFiles: ListFiles.fromJSON(object.reqListFiles) }
        : isSet(object.reqGetStatus)
        ? { $case: "reqGetStatus", reqGetStatus: GetStatus.fromJSON(object.reqGetStatus) }
        : isSet(object.reqAuth)
        ? { $case: "reqAuth", reqAuth: Auth.fromJSON(object.reqAuth) }
        : isSet(object.reqUploadFile)
        ? { $case: "reqUploadFile", reqUploadFile: UploadFile.fromJSON(object.reqUploadFile) }
        : isSet(object.reqGetFile)
        ? { $case: "reqGetFile", reqGetFile: GetFile.fromJSON(object.reqGetFile) }
        : isSet(object.reqDelFile)
        ? { $case: "reqDelFile", reqDelFile: DelFile.fromJSON(object.reqDelFile) }
        : undefined,
    };
  },

  toJSON(message: ReqEnvelope): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.payload?.$case === "reqListFiles") {
      obj.reqListFiles = ListFiles.toJSON(message.payload.reqListFiles);
    } else if (message.payload?.$case === "reqGetStatus") {
      obj.reqGetStatus = GetStatus.toJSON(message.payload.reqGetStatus);
    } else if (message.payload?.$case === "reqAuth") {
      obj.reqAuth = Auth.toJSON(message.payload.reqAuth);
    } else if (message.payload?.$case === "reqUploadFile") {
      obj.reqUploadFile = UploadFile.toJSON(message.payload.reqUploadFile);
    } else if (message.payload?.$case === "reqGetFile") {
      obj.reqGetFile = GetFile.toJSON(message.payload.reqGetFile);
    } else if (message.payload?.$case === "reqDelFile") {
      obj.reqDelFile = DelFile.toJSON(message.payload.reqDelFile);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReqEnvelope>, I>>(base?: I): ReqEnvelope {
    return ReqEnvelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReqEnvelope>, I>>(object: I): ReqEnvelope {
    const message = createBaseReqEnvelope();
    message.id = object.id ?? 0;
    switch (object.payload?.$case) {
      case "reqListFiles": {
        if (object.payload?.reqListFiles !== undefined && object.payload?.reqListFiles !== null) {
          message.payload = { $case: "reqListFiles", reqListFiles: ListFiles.fromPartial(object.payload.reqListFiles) };
        }
        break;
      }
      case "reqGetStatus": {
        if (object.payload?.reqGetStatus !== undefined && object.payload?.reqGetStatus !== null) {
          message.payload = { $case: "reqGetStatus", reqGetStatus: GetStatus.fromPartial(object.payload.reqGetStatus) };
        }
        break;
      }
      case "reqAuth": {
        if (object.payload?.reqAuth !== undefined && object.payload?.reqAuth !== null) {
          message.payload = { $case: "reqAuth", reqAuth: Auth.fromPartial(object.payload.reqAuth) };
        }
        break;
      }
      case "reqUploadFile": {
        if (object.payload?.reqUploadFile !== undefined && object.payload?.reqUploadFile !== null) {
          message.payload = {
            $case: "reqUploadFile",
            reqUploadFile: UploadFile.fromPartial(object.payload.reqUploadFile),
          };
        }
        break;
      }
      case "reqGetFile": {
        if (object.payload?.reqGetFile !== undefined && object.payload?.reqGetFile !== null) {
          message.payload = { $case: "reqGetFile", reqGetFile: GetFile.fromPartial(object.payload.reqGetFile) };
        }
        break;
      }
      case "reqDelFile": {
        if (object.payload?.reqDelFile !== undefined && object.payload?.reqDelFile !== null) {
          message.payload = { $case: "reqDelFile", reqDelFile: DelFile.fromPartial(object.payload.reqDelFile) };
        }
        break;
      }
    }
    return message;
  },
};

function createBaseRespEnvelope(): RespEnvelope {
  return { id: 0, error: false, errorMessage: "", payload: undefined };
}

export const RespEnvelope: MessageFns<RespEnvelope> = {
  encode(message: RespEnvelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.error !== false) {
      writer.uint32(16).bool(message.error);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    switch (message.payload?.$case) {
      case "respStatus":
        Status.encode(message.payload.respStatus, writer.uint32(82).fork()).join();
        break;
      case "respAck":
        Ack.encode(message.payload.respAck, writer.uint32(90).fork()).join();
        break;
      case "respFile":
        File.encode(message.payload.respFile, writer.uint32(98).fork()).join();
        break;
      case "respListOfFiles":
        ListOfFiles.encode(message.payload.respListOfFiles, writer.uint32(106).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RespEnvelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRespEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.error = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.payload = { $case: "respStatus", respStatus: Status.decode(reader, reader.uint32()) };
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.payload = { $case: "respAck", respAck: Ack.decode(reader, reader.uint32()) };
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.payload = { $case: "respFile", respFile: File.decode(reader, reader.uint32()) };
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.payload = { $case: "respListOfFiles", respListOfFiles: ListOfFiles.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RespEnvelope {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      error: isSet(object.error) ? globalThis.Boolean(object.error) : false,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "",
      payload: isSet(object.respStatus)
        ? { $case: "respStatus", respStatus: Status.fromJSON(object.respStatus) }
        : isSet(object.respAck)
        ? { $case: "respAck", respAck: Ack.fromJSON(object.respAck) }
        : isSet(object.respFile)
        ? { $case: "respFile", respFile: File.fromJSON(object.respFile) }
        : isSet(object.respListOfFiles)
        ? { $case: "respListOfFiles", respListOfFiles: ListOfFiles.fromJSON(object.respListOfFiles) }
        : undefined,
    };
  },

  toJSON(message: RespEnvelope): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.error !== false) {
      obj.error = message.error;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.payload?.$case === "respStatus") {
      obj.respStatus = Status.toJSON(message.payload.respStatus);
    } else if (message.payload?.$case === "respAck") {
      obj.respAck = Ack.toJSON(message.payload.respAck);
    } else if (message.payload?.$case === "respFile") {
      obj.respFile = File.toJSON(message.payload.respFile);
    } else if (message.payload?.$case === "respListOfFiles") {
      obj.respListOfFiles = ListOfFiles.toJSON(message.payload.respListOfFiles);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RespEnvelope>, I>>(base?: I): RespEnvelope {
    return RespEnvelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RespEnvelope>, I>>(object: I): RespEnvelope {
    const message = createBaseRespEnvelope();
    message.id = object.id ?? 0;
    message.error = object.error ?? false;
    message.errorMessage = object.errorMessage ?? "";
    switch (object.payload?.$case) {
      case "respStatus": {
        if (object.payload?.respStatus !== undefined && object.payload?.respStatus !== null) {
          message.payload = { $case: "respStatus", respStatus: Status.fromPartial(object.payload.respStatus) };
        }
        break;
      }
      case "respAck": {
        if (object.payload?.respAck !== undefined && object.payload?.respAck !== null) {
          message.payload = { $case: "respAck", respAck: Ack.fromPartial(object.payload.respAck) };
        }
        break;
      }
      case "respFile": {
        if (object.payload?.respFile !== undefined && object.payload?.respFile !== null) {
          message.payload = { $case: "respFile", respFile: File.fromPartial(object.payload.respFile) };
        }
        break;
      }
      case "respListOfFiles": {
        if (object.payload?.respListOfFiles !== undefined && object.payload?.respListOfFiles !== null) {
          message.payload = {
            $case: "respListOfFiles",
            respListOfFiles: ListOfFiles.fromPartial(object.payload.respListOfFiles),
          };
        }
        break;
      }
    }
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
