// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/strings/en/app.settings.json. DO NOT EDIT.
// Change the text there and run make i18n (i18n/README.md); the strings are in AppSettings.xcstrings.

import Foundation

extension S {
    /// Off The Cloud
    ///
    /// The product name, never translated.
    static var appSettingsBrand: String { L("app.settings.brand", table: "AppSettings") }

    /// Type "delete" to confirm.
    /// This can't be undone: C:\ & <b>bold</b> 100%
    ///
    /// Two lines with quotes, a backslash, an ampersand and a percent sign.
    static func appSettingsQuotes(b: AttributeContainer) -> AttributedString {
        LRich("app.settings.quotes", table: "AppSettings", tags: ["b": b], [])
    }

    /// {percent}% used of {total} GB
    ///
    /// Storage line in Settings.
    static func appSettingsStorageUsed(percent: Int, total: Int) -> String {
        L("app.settings.storage_used", table: "AppSettings", percent, total)
    }

    /// By continuing you accept the <terms>terms</terms> of {name}.
    ///
    /// Line under the sign-up button; the code links the terms.
    static func appSettingsTerms(name: String, terms: AttributeContainer) -> AttributedString {
        LRich("app.settings.terms", table: "AppSettings", tags: ["terms": terms], [.text(L10n.isolate(name))])
    }
}
