// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/strings/en/app.photos.json. DO NOT EDIT.
// Change the text there and run make i18n (i18n/README.md); the strings are in AppPhotos.xcstrings.

import Foundation

extension S {
    /// one: {count} photo
    /// other: {count} photos
    ///
    /// Number of photos under a collection's name.
    static func appPhotosCount(count: Int) -> String {
        L("app.photos.count", table: "AppPhotos", count)
    }

    /// one: {name} deleted a photo
    /// other: {name} deleted {count} photos
    ///
    /// Alert line in Notifications.
    static func appPhotosDeletedBy(name: String, count: Int) -> String {
        L("app.photos.deleted_by", table: "AppPhotos", L10n.isolate(name), count)
    }

    /// one: {name} deleted a photo from {place}
    /// other: {name} deleted {count} photos from {place}
    ///
    /// Alert line naming the collection the photos were in; one leaves out the number.
    static func appPhotosDeletedFrom(name: String, count: Int, place: String) -> String {
        L("app.photos.deleted_from", table: "AppPhotos", L10n.isolate(name), count, place)
    }

    /// {file}, shared by {name}
    ///
    /// Caption under a shared photo.
    static func appPhotosSharedBy(file: String, name: String) -> String {
        L("app.photos.shared_by", table: "AppPhotos", L10n.isolate(file), L10n.isolate(name))
    }

    /// Pick the photos to keep
    ///
    /// Title of the duplicate picker.
    static var appPhotosStale: String { L("app.photos.stale", table: "AppPhotos") }
}
