// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/strings/en/ios.json. DO NOT EDIT.
// Change the text there and run make i18n (i18n/README.md); the strings are in Ios.xcstrings.

import Foundation

extension S {
    /// Photos
    ///
    /// Tab bar item.
    static var iosTabPhotos: String { L("ios.tab.photos", table: "Ios") }
}
