// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/languages.json and i18n/strings. DO NOT EDIT.
//
// Change the catalog and run make i18n (i18n/README.md). The texts are in
// locales/<code>/<prefix>.json, one file per language and prefix (type
// Messages), for import.meta.glob. In a text:
//
//   {fileName}       an argument, by its name in MessageArgs: inserted as plain
//                    text, a number formatted with Intl first. A user argument
//                    is already between U+2068 and U+2069 (FSI ... PDI).
//   <link>...</link> a span of a RichKey, rendered by code; tags don't nest.
//
// No other "{", "}" or "<" appears. A PluralMessage's arg names the count:
// use forms[new Intl.PluralRules(tag).select(n)] ?? forms.other.

/** A language the generated locales hold (i18n/languages.json). */
export interface Language {
  /** Stored, sent on the wire and used in file names ("pt"). */
  readonly code: LanguageCode;
  /** The BCP 47 tag behind plural rules and formatters ("pt-PT"). */
  readonly tag: string;
  /** The language's own name, for the picker. */
  readonly name: string;
  readonly status: "shipping" | "draft";
}

export type LanguageCode =
  | "en";

/** English: the source, and the text of anything not translated. */
export const sourceLanguage: LanguageCode = "en";

/** The languages, English first. */
export const languages: readonly Language[] = [
  { code: "en", tag: "en", name: "English", status: "shipping" },
];

/** A text with a count: one form per plural category, other as the fallback. */
export interface PluralMessage {
  readonly one: string;
  readonly other: string;
  /** The argument that picks the form. */
  readonly arg: string;
}

/** A locale file: key -> text. */
export type Messages = Readonly<Record<string, string | PluralMessage>>;

/** The keys t() looks up: every web key without tags. */
export type MessageKey =
  | "common.accept"
  | "common.add"
  | "common.apply"
  | "common.back"
  | "common.cancel"
  | "common.choose"
  | "common.close"
  | "common.connect"
  | "common.connecting"
  | "common.create"
  | "common.decline"
  | "common.delete"
  | "common.deleting"
  | "common.deselect"
  | "common.disconnect"
  | "common.done"
  | "common.download"
  | "common.loading"
  | "common.next"
  | "common.ok"
  | "common.open"
  | "common.password"
  | "common.pause"
  | "common.quit"
  | "common.refresh"
  | "common.remove"
  | "common.rename"
  | "common.resume"
  | "common.save"
  | "common.search"
  | "common.select"
  | "common.send"
  | "common.settings"
  | "common.share"
  | "common.try_again"
  | "common.update"
  | "common.updating"
  | "common.upload";

/** The keys <Trans> renders: every web key with tags. */
export type RichKey = never;

/** Each key's arguments by name; undefined when it takes none. */
export interface MessageArgs {
  "common.accept": undefined;
  "common.add": undefined;
  "common.apply": undefined;
  "common.back": undefined;
  "common.cancel": undefined;
  "common.choose": undefined;
  "common.close": undefined;
  "common.connect": undefined;
  "common.connecting": undefined;
  "common.create": undefined;
  "common.decline": undefined;
  "common.delete": undefined;
  "common.deleting": undefined;
  "common.deselect": undefined;
  "common.disconnect": undefined;
  "common.done": undefined;
  "common.download": undefined;
  "common.loading": undefined;
  "common.next": undefined;
  "common.ok": undefined;
  "common.open": undefined;
  "common.password": undefined;
  "common.pause": undefined;
  "common.quit": undefined;
  "common.refresh": undefined;
  "common.remove": undefined;
  "common.rename": undefined;
  "common.resume": undefined;
  "common.save": undefined;
  "common.search": undefined;
  "common.select": undefined;
  "common.send": undefined;
  "common.settings": undefined;
  "common.share": undefined;
  "common.try_again": undefined;
  "common.update": undefined;
  "common.updating": undefined;
  "common.upload": undefined;
}

/** Each rich key's tags. */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface RichTags {}

/**
 * What follows the key in a lookup of K: nothing, or its arguments, as in
 * t<K extends MessageKey>(key: K, ...args: ArgsOf<K>).
 */
export type ArgsOf<K extends keyof MessageArgs> = MessageArgs[K] extends undefined ? [] : [args: MessageArgs[K]];
