// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/strings/en/common.json. DO NOT EDIT.
// Change the text there and run make i18n (i18n/README.md); the strings are in Common.xcstrings.

import Foundation

extension S {
    /// Cancel
    ///
    /// Button that closes a dialog.
    static var commonCancel: String { L("common.cancel", table: "Common") }

    /// Loading…
    ///
    /// Shown while a page loads.
    static var commonLoading: String { L("common.loading", table: "Common") }
}
