// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/strings/en/desk.json. DO NOT EDIT.
// Change the text there and run make i18n (i18n/README.md); the strings are in Desk.xcstrings.

import Foundation

extension S {
    /// one: Syncing {count} folder
    /// other: Syncing {count} folders
    ///
    /// Status line in the menu.
    static func deskFoldersSyncing(count: Int) -> String {
        L("desk.folders.syncing", table: "Desk", count)
    }
}
