// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Code generated by i18ngen from i18n/strings/en/desk.main.json. DO NOT EDIT.
// Change the text there and run make i18n (i18n/README.md); the strings are in DeskMain.xcstrings.

import Foundation

extension S {
    /// Language
    ///
    /// Label of the language picker in the Mac app's Settings, and title of the Language submenu in otc-sync's tray menu (Windows and Linux). The choice applies to every Off The Cloud app.
    static var deskMainLanguage: String { L("desk.main.language", table: "DeskMain") }

    /// Automatic ({language})
    ///
    /// First choice of the language picker: follow the computer's own language. {language} is the language that gives, written by its own name (for example Español); language names are never translated.
    static func deskMainLanguageAutomatic(language: String) -> String {
        L("desk.main.language_automatic", table: "DeskMain", language)
    }
}
