// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by i18ngen from i18n/languages.json; DO NOT EDIT.

package i18n

// languages are the languages this build carries, English first: the
// shipping ones (make i18n DRAFT=1 adds the drafts and the pseudo-locale).
var languages = []Language{
	{Code: "en", Tag: "en", Name: "English"},
}
