// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by i18ngen from i18n/strings/en/common.json; DO NOT EDIT.

package i18n

// CommonAccept is common.accept: "Accept".
func CommonAccept() Msg {
	return Msg{Key: "common.accept"}
}

// CommonAdd is common.add: "Add".
func CommonAdd() Msg {
	return Msg{Key: "common.add"}
}

// CommonApply is common.apply: "Apply".
func CommonApply() Msg {
	return Msg{Key: "common.apply"}
}

// CommonBack is common.back: "Back".
func CommonBack() Msg {
	return Msg{Key: "common.back"}
}

// CommonCancel is common.cancel: "Cancel".
func CommonCancel() Msg {
	return Msg{Key: "common.cancel"}
}

// CommonChoose is common.choose: "Choose".
func CommonChoose() Msg {
	return Msg{Key: "common.choose"}
}

// CommonClose is common.close: "Close".
func CommonClose() Msg {
	return Msg{Key: "common.close"}
}

// CommonConnect is common.connect: "Connect".
func CommonConnect() Msg {
	return Msg{Key: "common.connect"}
}

// CommonConnecting is common.connecting: "Connecting…".
func CommonConnecting() Msg {
	return Msg{Key: "common.connecting"}
}

// CommonCreate is common.create: "Create".
func CommonCreate() Msg {
	return Msg{Key: "common.create"}
}

// CommonDecline is common.decline: "Decline".
func CommonDecline() Msg {
	return Msg{Key: "common.decline"}
}

// CommonDelete is common.delete: "Delete".
func CommonDelete() Msg {
	return Msg{Key: "common.delete"}
}

// CommonDeleting is common.deleting: "Deleting…".
func CommonDeleting() Msg {
	return Msg{Key: "common.deleting"}
}

// CommonDeselect is common.deselect: "Deselect".
func CommonDeselect() Msg {
	return Msg{Key: "common.deselect"}
}

// CommonDisconnect is common.disconnect: "Disconnect".
func CommonDisconnect() Msg {
	return Msg{Key: "common.disconnect"}
}

// CommonDone is common.done: "Done".
func CommonDone() Msg {
	return Msg{Key: "common.done"}
}

// CommonDownload is common.download: "Download".
func CommonDownload() Msg {
	return Msg{Key: "common.download"}
}

// CommonLoading is common.loading: "Loading…".
func CommonLoading() Msg {
	return Msg{Key: "common.loading"}
}

// CommonNext is common.next: "Next".
func CommonNext() Msg {
	return Msg{Key: "common.next"}
}

// CommonOk is common.ok: "OK".
func CommonOk() Msg {
	return Msg{Key: "common.ok"}
}

// CommonOpen is common.open: "Open".
func CommonOpen() Msg {
	return Msg{Key: "common.open"}
}

// CommonPassword is common.password: "Password".
func CommonPassword() Msg {
	return Msg{Key: "common.password"}
}

// CommonPause is common.pause: "Pause".
func CommonPause() Msg {
	return Msg{Key: "common.pause"}
}

// CommonQuit is common.quit: "Quit".
func CommonQuit() Msg {
	return Msg{Key: "common.quit"}
}

// CommonRefresh is common.refresh: "Refresh".
func CommonRefresh() Msg {
	return Msg{Key: "common.refresh"}
}

// CommonRemove is common.remove: "Remove".
func CommonRemove() Msg {
	return Msg{Key: "common.remove"}
}

// CommonRename is common.rename: "Rename".
func CommonRename() Msg {
	return Msg{Key: "common.rename"}
}

// CommonResume is common.resume: "Resume".
func CommonResume() Msg {
	return Msg{Key: "common.resume"}
}

// CommonSave is common.save: "Save".
func CommonSave() Msg {
	return Msg{Key: "common.save"}
}

// CommonSearch is common.search: "Search".
func CommonSearch() Msg {
	return Msg{Key: "common.search"}
}

// CommonSelect is common.select: "Select".
func CommonSelect() Msg {
	return Msg{Key: "common.select"}
}

// CommonSend is common.send: "Send".
func CommonSend() Msg {
	return Msg{Key: "common.send"}
}

// CommonSettings is common.settings: "Settings".
func CommonSettings() Msg {
	return Msg{Key: "common.settings"}
}

// CommonShare is common.share: "Share".
func CommonShare() Msg {
	return Msg{Key: "common.share"}
}

// CommonTryAgain is common.try_again: "Try again".
func CommonTryAgain() Msg {
	return Msg{Key: "common.try_again"}
}

// CommonUpdate is common.update: "Update".
func CommonUpdate() Msg {
	return Msg{Key: "common.update"}
}

// CommonUpdating is common.updating: "Updating…".
func CommonUpdating() Msg {
	return Msg{Key: "common.updating"}
}

// CommonUpload is common.upload: "Upload".
func CommonUpload() Msg {
	return Msg{Key: "common.upload"}
}
