// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by i18ngen from i18n/strings/en/desk.main.json; DO NOT EDIT.

package i18n

// DeskMainLanguage is desk.main.language: "Language".
func DeskMainLanguage() Msg {
	return Msg{Key: "desk.main.language"}
}

// DeskMainLanguageAutomatic is desk.main.language_automatic: "Automatic ({language})".
func DeskMainLanguageAutomatic(language string) Msg {
	return Msg{Key: "desk.main.language_automatic", Args: map[string]any{"language": language}}
}
