// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/strings/en/android.json. DO NOT EDIT.
// Change the catalog and run make i18n (i18n/README.md).

package cloud.offthe.otc.i18n

import cloud.offthe.otc.R

/** "@home is where the photos are": Starts with an at sign (a resource reference to aapt2). */
fun S.androidEscAt(): UiText =
    UiText.Res(R.string.android_esc_at)

/** "Off The Cloud {version}": Never translated. Never translated. */
fun S.androidEscFixed(version: String): UiText =
    UiText.Res(R.string.android_esc_fixed, listOf(version))

/** "{name} first": Starts with a user argument. */
fun S.androidEscLeadingArg(name: String): UiText =
    UiText.Res(R.string.android_esc_leading_arg, listOf(name))

/** "First line\nSecond line": Two lines. */
fun S.androidEscLines(): UiText =
    UiText.Res(R.string.android_esc_lines)

/** "Fish & chips > fries": An ampersand and a greater-than sign. */
fun S.androidEscMarkup(): UiText =
    UiText.Res(R.string.android_esc_markup)

/** "100% sure": A percent sign without arguments. */
fun S.androidEscPercent(): UiText =
    UiText.Res(R.string.android_esc_percent)

/** "{name} is 100% sure, %s%n and $& stay text": A percent sign with arguments, and format-looking text. */
fun S.androidEscPercentArgs(name: String): UiText =
    UiText.Res(R.string.android_esc_percent_args, listOf(name))

/** "?! is not a question": Starts with a question mark (an attribute reference to aapt2). */
fun S.androidEscQuestion(): UiText =
    UiText.Res(R.string.android_esc_question)

/** "It's "quoted", with a back\slash": Quotes, an apostrophe and a backslash. */
fun S.androidEscQuotes(): UiText =
    UiText.Res(R.string.android_esc_quotes)

/** "{list_of} and {s} in {r}": Argument names that could shadow names in the accessor. */
fun S.androidEscShadow(listOf: String, s: String, r: Int): UiText =
    UiText.Res(R.string.android_esc_shadow, listOf(listOf, s, r))

/** "Keep 10\u00A0GB free, «\u202Fok\u202F»": A no-break space and narrow no-break spaces. */
fun S.androidEscSpaces(): UiText =
    UiText.Res(R.string.android_esc_spaces)

/** "Connecting… ¿Qué? 😀 ñ": Non-ASCII text. */
fun S.androidEscUnicode(): UiText =
    UiText.Res(R.string.android_esc_unicode)
