// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/strings/en/app.photos.json. DO NOT EDIT.
// Change the catalog and run make i18n (i18n/README.md).

package cloud.offthe.otc.i18n

import cloud.offthe.otc.R

/** "{count} photos" (one: "{count} photo"): Under a collection's name. */
fun S.appPhotosCount(count: Int): UiText =
    UiText.Plural(R.plurals.app_photos_count, count, listOf(count))

/** "{name} deleted {count} photos" (one: "{name} deleted a photo"): Alert line in Notifications. */
fun S.appPhotosDeletedBy(name: String, count: Int): UiText =
    UiText.Plural(R.plurals.app_photos_deleted_by, count, listOf(name, count))

/** "Read the <link>privacy policy</link> before sharing <b>{file_name}</b>": Above the share button; link opens the policy. Tags: b, link. */
fun S.appPhotosPrivacy(fileName: String): RichText =
    RichText.Res(R.string.app_photos_privacy, listOf(fileName))

/** "<b>{count} photos</b> were removed" (one: "<b>A photo</b> was removed"): Banner after a deletion. Tags: b. */
fun S.appPhotosRemoved(count: Int): RichText =
    RichText.Plural(R.plurals.app_photos_removed, count, listOf(count))

/** "Used {used} of {total} slots": Storage line. */
fun S.appPhotosSlots(used: Int, total: Int): UiText =
    UiText.Res(R.string.app_photos_slots, listOf(used, total))
