// SPDX-License-Identifier: AGPL-3.0-or-later
// Code generated by i18ngen from i18n/strings/en/common.json. DO NOT EDIT.
// Change the catalog and run make i18n (i18n/README.md).

package cloud.offthe.otc.i18n

import cloud.offthe.otc.R

/** "Cancel": Button that closes a dialog. */
fun S.commonCancel(): UiText =
    UiText.Res(R.string.common_cancel)

/** "Save": Button that saves a form. */
fun S.commonSave(): UiText =
    UiText.Res(R.string.common_save)
