// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/alonsovidales/otc/i18n/model"
)

var goUpdate = flag.Bool("update-go", false, "rewrite the Go emitter's golden files and package i18n's test catalog")

// goFixture is package i18n's test catalog (i18n/testdata/src), whose
// generated catalog (i18n/testdata/catalog) the runtime's tests read.
const goFixture = "../../testdata/src"

func goLoadChecked(t *testing.T, root string) *model.Catalog {
	t.Helper()
	cat, err := model.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	ds := append(cat.Check(model.CheckOptions{}), cat.NonCanonical(model.CheckOptions{})...)
	for _, d := range ds {
		if d.Severity == model.Error {
			t.Errorf("%s", d)
		}
	}
	return cat
}

func goEmit(t *testing.T, cat *model.Catalog, draft bool) map[string][]byte {
	t.Helper()
	out, err := goEmitter{}.Emit(cat, Options{Root: cat.Root(), Draft: draft, Languages: cat.OutputLanguages(draft, nil)})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

// TestGoRuntimeFixture generates package i18n's test catalog and compares
// it, and the constructors and language table, with what is committed:
// the runtime's tests read exactly what this emitter writes. -update-go
// rewrites them.
func TestGoRuntimeFixture(t *testing.T) {
	out := goEmit(t, goLoadChecked(t, goFixture), false)
	golden := map[string]string{} // generated path -> committed file
	for p := range out {
		switch {
		case strings.HasPrefix(p, goCatalogDir+"/"):
			golden[p] = filepath.Join("../../testdata/catalog", strings.TrimPrefix(p, goCatalogDir+"/"))
		default:
			golden[p] = filepath.Join("testdata/go", filepath.Base(p)+".golden")
		}
	}
	if *goUpdate {
		os.RemoveAll("../../testdata/catalog")
		for p, file := range golden {
			os.MkdirAll(filepath.Dir(file), 0o755)
			if err := os.WriteFile(file, out[p], 0o644); err != nil {
				t.Fatal(err)
			}
		}
	}
	for p, file := range golden {
		have, err := os.ReadFile(file)
		if err != nil || !bytes.Equal(have, out[p]) {
			t.Errorf("%s differs from what the emitter writes for %s (go test -run TestGoRuntimeFixture -update-go):\n%s", file, p, out[p])
		}
	}
	want := []string{
		"i18n/catalog/de/common.json", "i18n/catalog/en/dev.json", "i18n/catalog/pt/site.json",
		"i18n/languages_gen.go", "i18n/msg_common_gen.go", "i18n/msg_desk_gen.go", "i18n/msg_dev_gen.go",
		"i18n/msg_push_gen.go", "i18n/msg_site_gen.go",
	}
	for _, p := range want {
		if out[p] == nil {
			t.Errorf("%s not generated", p)
		}
	}
	for p := range out {
		if strings.Contains(p, "/nl/") || strings.Contains(p, "wiz") {
			t.Errorf("%s: a draft language or a wizard prefix reached the Go catalog", p)
		}
	}
}

// What the fixture's English and Spanish files hold.
func TestGoCatalogContent(t *testing.T) {
	out := goEmit(t, goLoadChecked(t, goFixture), false)
	var en map[string]struct {
		Text json.RawMessage
		Args [][]string
	}
	if err := json.Unmarshal(out["i18n/catalog/en/dev.json"], &en); err != nil {
		t.Fatal(err)
	}
	if got := en["dev.photos_deleted"].Args; !slices.EqualFunc(got, [][]string{{"name", "user"}, {"count", "count"}}, slices.Equal) {
		t.Errorf("English declares %v", got)
	}
	es := string(out["i18n/catalog/es/dev.json"])
	for _, want := range []string{
		`"dev.photos_deleted": {"text": {"one": "{name} borró una foto", "other": "{name} borró {count} fotos"}}`,
		`"dev.literal": {"text": "El 100% del \"espacio\" de {name} & $1 $& %s%n \\ hecho"}`,
	} {
		if !strings.Contains(es, want) {
			t.Errorf("es/dev.json lacks %s:\n%s", want, es)
		}
	}
	// Missing and stale translations are left to the English file.
	if strings.Contains(es, "dev.stale") || strings.Contains(es, "dev.only_en") {
		t.Errorf("es/dev.json copies English:\n%s", es)
	}
	if got := string(out["i18n/catalog/de/common.json"]); got != "{\n}\n" {
		t.Errorf("a language without translations: %q", got)
	}
	if strings.Contains(es, `"args"`) {
		t.Error("a translation declares arguments; only English does")
	}
	gen := string(out["i18n/msg_dev_gen.go"])
	for _, want := range []string{
		"func DevPhotosDeleted(name string, count int) Msg {\n\treturn Msg{Key: \"dev.photos_deleted\", Args: map[string]any{\"name\": name, \"count\": int64(count)}}\n}",
		"func DevLastSeen(at time.Time) Msg {",
		`"at": at.Unix()`,
		"func DevFreeSpace(free int64, total int64) Msg {",
		"func DevDiskFailed(port string, reason Msg) Msg {",
		`"reason": reason.Key`,
		"func DevOnlyEn() Msg {\n\treturn Msg{Key: \"dev.only_en\"}\n}",
		"import \"time\"",
		"// Code generated by i18ngen from i18n/strings/en/dev.json; DO NOT EDIT.",
	} {
		if !strings.Contains(gen, want) {
			t.Errorf("msg_dev_gen.go lacks %q:\n%s", want, gen)
		}
	}
	if site := string(out["i18n/msg_site_gen.go"]); !strings.Contains(site, "func SitePrivacy(name string) Rich {") {
		t.Errorf("a rich key's constructor must return Rich:\n%s", site)
	}
	if strings.Contains(string(out["i18n/msg_common_gen.go"]), "import") {
		t.Error("msg_common_gen.go imports time without a datetime argument")
	}
}

func TestGoDraftOutput(t *testing.T) {
	out := goEmit(t, goLoadChecked(t, goFixture), true)
	for p, data := range out {
		if !bytes.Contains(data, []byte(DraftMarker)) {
			t.Errorf("%s lacks the draft marker", p)
		}
	}
	for _, p := range []string{"i18n/catalog/nl/common.json", "i18n/catalog/qps/dev.json"} {
		if out[p] == nil {
			t.Errorf("draft output lacks %s", p)
		}
	}
	if !strings.Contains(string(out["i18n/catalog/nl/common.json"]), `"common.cancel": {"text": "Annuleren"}`) {
		t.Errorf("nl draft lacks its translation:\n%s", out["i18n/catalog/nl/common.json"])
	}
	if !strings.Contains(string(out[goLanguagesFile]), `{Code: "qps", Tag: "en-XA", Name: "Pseudo"}`) {
		t.Errorf("draft languages lack the pseudo-locale:\n%s", out[goLanguagesFile])
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(out["i18n/catalog/qps/dev.json"], &m); err != nil || m[goDraftKey] == nil {
		t.Errorf("draft catalog file: %v %s", err, out["i18n/catalog/qps/dev.json"])
	}
}

// goHostileLanguages routes a root to the Go programs for hostile-catalog
// tests.
const goHostileLanguages = `{
  "languages": [
    {"code": "en", "tag": "en", "apple": "en", "android": "", "name": "English", "status": "shipping"},
    {"code": "es", "tag": "es", "apple": "es", "android": "es", "name": "Español", "status": "shipping"}
  ],
  "routes": {"dev": ["go"], "site": ["go"], "common": ["otcsync", "wizard"], "wiz": ["wizard"]}
}
`

// goHostileTexts tokenize (so an emitter can't refuse them) yet mean
// something to Go, JSON, Python, HTML, printf or a regexp replacement.
var goHostileTexts = []string{
	`"""`, `'''`, `\`, `\\"`, "`` `", `$& $1 $$`, `%s%n%v %!`, `*/ /*`, `//go:generate rm -rf`,
	"x\nvar _ = os.Exit\n//", "x\r\npackage main", "\u2028\u2029\u0085", "\x00", "\ufeff",
	"\U0001F600 é ü", `# END GENERATED I18N`, "\n# END GENERATED I18N\nimport os\nI18N = None\n#",
	`\u0041 \x41 \N \t \U0001F600`, `" + __import__("os").system("id") + "`, `--> ]]>`, `& &amp; &#x3c;`, `>`,
}

// goHostileRepo writes a catalog holding every hostile text as an English
// text and as its Spanish translation. Check would refuse much of it;
// Emit is called directly.
func goHostileRepo(t *testing.T, root string, extra map[string]string) string {
	t.Helper()
	var en, es, wen, wes []string
	for i, s := range goHostileTexts {
		js := goJSONString(s)
		en = append(en, `"`+root+`.h`+goHostileID(i)+`": {"text": `+js+`, "note": "n"}`)
		es = append(es, `"`+root+`.h`+goHostileID(i)+`": {"text": `+js+`, "en": `+js+`}`)
		wen = append(wen, `"wiz.h`+goHostileID(i)+`": {"text": `+js+`, "note": "n"}`)
		wes = append(wes, `"wiz.h`+goHostileID(i)+`": {"text": `+js+`, "en": `+js+`}`)
	}
	files := map[string]string{
		model.LanguagesFile:                 goHostileLanguages,
		"i18n/strings/en/" + root + ".json": "{" + strings.Join(en, ",\n") + "}\n",
		"i18n/strings/es/" + root + ".json": "{" + strings.Join(es, ",\n") + "}\n",
		"i18n/strings/en/wiz.json":          "{" + strings.Join(wen, ",\n") + "}\n",
		"i18n/strings/es/wiz.json":          "{" + strings.Join(wes, ",\n") + "}\n",
		"i18n/strings/en/common.json":       `{"common.ok": {"text": "OK", "note": "n"}}`,
		"i18n/strings/en/site.json":         `{"site.x": {"text": "<script>alert(1)</script> {name}", "args": [["name", "user"]], "note": "n", "rich": ["script"]}}`,
		"scripts/setup_wizard.py":           wizardSample,
		"i18n/strings/es/site.json":         `{"site.x": {"text": "<script>alert(2)</script> {name}", "en": "<script>alert(1)</script> {name}"}}`,
	}
	for k, v := range extra {
		files[k] = v
	}
	return writeRepo(t, files)
}

func goHostileID(i int) string { return string(rune('a'+i/26)) + string(rune('a'+i%26)) }

// Hostile text comes out of the Go emitter as data: the JSON holds it
// exactly, and the Go code is only the constructors, the text quoted in
// their comments.
func TestGoEmitterHostileCatalog(t *testing.T) {
	cat, err := model.Load(goHostileRepo(t, "dev", nil))
	if err != nil {
		t.Fatal(err)
	}
	out, err := goEmitter{}.Emit(cat, Options{Languages: cat.OutputLanguages(false, nil)})
	if err != nil {
		t.Fatal(err)
	}
	for _, code := range []string{"en", "es"} {
		var m map[string]struct{ Text string }
		if err := json.Unmarshal(out["i18n/catalog/"+code+"/dev.json"], &m); err != nil {
			t.Fatalf("%s: %v", code, err)
		}
		for i, s := range goHostileTexts {
			if got := m["dev.h"+goHostileID(i)].Text; got != s {
				t.Errorf("%s dev.h%s = %q, want %q", code, goHostileID(i), got, s)
			}
		}
	}
	src := out["i18n/msg_dev_gen.go"]
	f, err := parser.ParseFile(token.NewFileSet(), "msg_dev_gen.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("generated Go doesn't parse: %v\n%s", err, src)
	}
	var funcs []string
	for _, d := range f.Decls {
		fd, ok := d.(*ast.FuncDecl)
		if !ok || fd.Recv != nil || len(fd.Body.List) != 1 {
			t.Fatalf("unexpected declaration in generated Go:\n%s", src)
		}
		if _, ok := fd.Body.List[0].(*ast.ReturnStmt); !ok {
			t.Fatalf("%s does more than return its message:\n%s", fd.Name.Name, src)
		}
		funcs = append(funcs, fd.Name.Name)
	}
	if len(funcs) != len(goHostileTexts) || f.Imports != nil {
		t.Errorf("generated %d functions and imports %v for %d keys:\n%s", len(funcs), f.Imports, len(goHostileTexts), src)
	}
	for _, cg := range f.Comments {
		for _, c := range cg.List {
			if !strings.HasPrefix(c.Text, "// Dev") && !strings.HasPrefix(c.Text, "// SPDX") && !strings.HasPrefix(c.Text, "// Code generated") {
				t.Errorf("a text escaped its comment: %q", c.Text)
			}
		}
	}
	for _, want := range []string{`// DevHab is dev.hab: "'\x27'".`, "// DevHae is dev.hae: \"`\\x60 `\"."} {
		if !strings.Contains(string(src), want) {
			t.Errorf("generated Go lacks %s", want)
		}
	}
	// A rich key's tags are data too, whatever they are called.
	if !strings.Contains(string(out["i18n/catalog/es/site.json"]), `"<script>alert(2)</script> {name}"`) {
		t.Errorf("site.x: %s", out["i18n/catalog/es/site.json"])
	}
}

// What doesn't tokenize, or would make wrong code, is an error, never
// output.
func TestGoEmitterRefuses(t *testing.T) {
	cases := map[string]string{
		"markup":       `{"dev.x": {"text": "</script><img onerror=alert(1)>", "note": "n"}}`,
		"template":     `{"dev.x": {"text": "{{.}}", "note": "n"}}`,
		"undeclared":   `{"dev.x": {"text": "{name}", "note": "n"}}`,
		"tag":          `{"dev.x": {"text": "<b>x</b>", "note": "n"}}`,
		"keyword":      `{"dev.x": {"text": "{type}", "args": [["type", "text"]], "note": "n"}}`,
		"type":         `{"dev.x": {"text": "{n}", "args": [["n", "float"]], "note": "n"}}`,
		"runtime name": `{"format.int": {"text": "x", "note": "n"}}`,
	}
	for name, src := range cases {
		t.Run(name, func(t *testing.T) {
			file := "i18n/strings/en/dev.json"
			langs := goHostileLanguages
			if name == "runtime name" {
				file = "i18n/strings/en/format.json"
				langs = strings.Replace(langs, `"dev": ["go"]`, `"format": ["go"]`, 1)
			}
			root := writeRepo(t, map[string]string{model.LanguagesFile: langs, file: src})
			cat, err := model.Load(root)
			if err != nil {
				t.Fatal(err)
			}
			if out, err := (goEmitter{}).Emit(cat, Options{Languages: cat.OutputLanguages(false, nil)}); err == nil {
				t.Errorf("emitted instead of refusing:\n%s", out["i18n/msg_dev_gen.go"])
			}
		})
	}
}

// goRuntimeNames lists exactly the exported names of package i18n's own
// code, so a constructor can never redeclare one.
func TestGoRuntimeNames(t *testing.T) {
	files, _ := filepath.Glob("../../*.go")
	var names []string
	for _, file := range files {
		if strings.HasSuffix(file, "_gen.go") || strings.HasSuffix(file, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(token.NewFileSet(), file, nil, parser.SkipObjectResolution)
		if err != nil {
			t.Fatal(err)
		}
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.FuncDecl:
				if d.Recv == nil && d.Name.IsExported() {
					names = append(names, d.Name.Name)
				}
			case *ast.GenDecl:
				for _, s := range d.Specs {
					switch s := s.(type) {
					case *ast.TypeSpec:
						if s.Name.IsExported() {
							names = append(names, s.Name.Name)
						}
					case *ast.ValueSpec:
						for _, n := range s.Names {
							if n.IsExported() {
								names = append(names, n.Name)
							}
						}
					}
				}
			}
		}
	}
	sort.Strings(names)
	want := slices.Clone(goRuntimeNames)
	sort.Strings(want)
	if !slices.Equal(names, want) {
		t.Errorf("package i18n exports %v; goRuntimeNames is %v", names, want)
	}
}

// The constructors compile against the real runtime: the fixture's
// generated files (every argument type, a rich key) and a hostile
// catalog's stand in for the committed ones through an overlay.
func TestGoConstructorsCompile(t *testing.T) {
	if testing.Short() {
		t.Skip("runs the go command")
	}
	gobin, err := exec.LookPath("go")
	if err != nil {
		t.Skip("no go command")
	}
	cat, err := model.Load(goHostileRepo(t, "dev", nil))
	if err != nil {
		t.Fatal(err)
	}
	hostile, err := goEmitter{}.Emit(cat, Options{Languages: cat.OutputLanguages(false, nil)})
	if err != nil {
		t.Fatal(err)
	}
	fixture := goEmit(t, goLoadChecked(t, goFixture), false)
	pkg, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	replace := map[string]string{}
	// The committed constructors give way to the fixture's (which has
	// common keys of its own) and the hostile catalog's.
	committed, _ := filepath.Glob(filepath.Join(pkg, "msg_*_gen.go"))
	for _, f := range committed {
		replace[f] = ""
	}
	replace[filepath.Join(pkg, "embedded_test.go")] = "" // tests the committed constructors
	add := func(name string, data []byte) {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, data, 0o644); err != nil {
			t.Fatal(err)
		}
		replace[filepath.Join(pkg, name)] = p
	}
	for p, data := range fixture {
		if strings.HasSuffix(p, ".go") {
			add(filepath.Base(p), data)
		}
	}
	add("msg_hostile_gen.go", bytes.Replace(hostile["i18n/msg_dev_gen.go"], []byte("func Dev"), []byte("func HostileDev"), -1))
	ov, _ := json.Marshal(map[string]any{"Replace": replace})
	ovFile := filepath.Join(dir, "overlay.json")
	if err := os.WriteFile(ovFile, ov, 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(gobin, "vet", "-overlay", ovFile, ".")
	cmd.Dir = pkg
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated constructors don't compile: %v\n%s", err, out)
	}
}
