// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"fmt"
	"regexp"
	"strings"
	"unicode"

	"github.com/alonsovidales/otc/i18n/model"
)

// The Swift side: S+<Table>.swift and Languages.swift. No catalog text is
// ever written into Swift source as code or a string literal: keys and
// table names are identifiers checked against strict patterns here, the
// English text and the note appear only in doc comments, cleaned of line
// breaks and of the invisible characters that could make a line read
// differently from what it compiles to.

var (
	appleArgPattern   = regexp.MustCompile(`^[a-z][a-z0-9]*(_[a-z0-9]+)*$`)
	appleTagPattern   = regexp.MustCompile(`^[a-z][a-z0-9]*$`)
	appleTablePattern = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)
)

// appleDraftLine marks a Swift file written by make i18n DRAFT=1.
const appleDraftLine = "// " + DraftMarker + ": draft languages included (make i18n DRAFT=1); run make i18n before committing.\n"

// appleAccessors writes S+<Table>.swift: an extension of the S namespace
// (declared in L10n.swift) with one accessor per key.
//
//   - A key without arguments is a property: S.commonCancel.
//   - With arguments, a function taking them in their declared order:
//     S.appPhotosDeletedBy(name: String, count: Int). text and user
//     arguments are String, count and int are Int. user arguments are
//     wrapped in Unicode isolation marks (L10n.isolate), so that a name in
//     another script doesn't reorder the sentence around it.
//   - A key with tags returns an AttributedString and also takes one
//     AttributeContainer per tag, which styles the text inside that tag:
//     S.appLegalTerms(terms: AttributeContainer().link(url)). LRich in
//     L10n.swift renders it.
func appleAccessors(entries []*model.Entry, prefix, table, consumer string, draft bool) ([]byte, error) {
	if !appleTablePattern.MatchString(table) {
		return nil, fmt.Errorf("prefix %s: %q is not a table name", prefix, table)
	}
	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-or-later\n//\n")
	fmt.Fprintf(&b, "// Code generated by i18ngen from %s/%s/%s.json. DO NOT EDIT.\n", model.StringsDir, model.SourceCode, prefix)
	b.WriteString("// Change the text there and run make i18n (i18n/README.md); the strings are in " + table + ".xcstrings.\n")
	if draft {
		b.WriteString(appleDraftLine)
	}
	b.WriteString("\nimport Foundation\n\nextension S {\n")
	for i, e := range entries {
		if i > 0 {
			b.WriteString("\n")
		}
		if err := appleAccessor(&b, e, table, consumer); err != nil {
			return nil, fmt.Errorf("%s: %w", e.Key, err)
		}
	}
	b.WriteString("}\n")
	return []byte(b.String()), nil
}

func appleAccessor(b *strings.Builder, e *model.Entry, table, consumer string) error {
	if !model.KeyPattern.MatchString(e.Key) {
		return fmt.Errorf("not a valid key")
	}
	name := model.CamelName(e.Key)
	var params, plain, rich []string
	labels := map[string]bool{}
	for _, a := range e.Args {
		if !appleArgPattern.MatchString(a.Name) {
			return fmt.Errorf("argument %q is not a valid name", a.Name)
		}
		l := model.ArgName(a.Name)
		labels[l] = true
		switch a.Type {
		case model.ArgText:
			params, plain, rich = append(params, l+": String"), append(plain, l), append(rich, ".text("+l+")")
		case model.ArgUser:
			params, plain, rich = append(params, l+": String"), append(plain, "L10n.isolate("+l+")"), append(rich, ".text(L10n.isolate("+l+"))")
		case model.ArgCount, model.ArgInt:
			params, plain, rich = append(params, l+": Int"), append(plain, l), append(rich, ".int("+l+")")
		default:
			return fmt.Errorf("argument %q: the Apple apps can't show a %s argument", a.Name, a.Type)
		}
	}

	appleDoc(b, e)
	call := fmt.Sprintf("%s, table: %s", swiftQuote(e.Key), swiftQuote(table))
	switch {
	case e.IsRich():
		var tags []string
		for _, t := range e.Rich {
			switch {
			case !appleTagPattern.MatchString(t):
				return fmt.Errorf("tag %q is not a valid name", t)
			case labels[t]:
				return fmt.Errorf("tag <%s> has the name of an argument: rename one (the accessor takes both)", t)
			case len(model.ReservedIn(t, []string{consumer})) > 0:
				return fmt.Errorf("tag <%s> is a Swift keyword: rename it (the accessor takes it as a parameter)", t)
			}
			labels[t] = true
			params = append(params, t+": AttributeContainer")
			tags = append(tags, swiftQuote(t)+": "+t)
		}
		fmt.Fprintf(b, "    static func %s(%s) -> AttributedString {\n", name, strings.Join(params, ", "))
		fmt.Fprintf(b, "        LRich(%s, tags: [%s], [%s])\n    }\n", call, strings.Join(tags, ", "), strings.Join(rich, ", "))
	case len(e.Args) == 0:
		fmt.Fprintf(b, "    static var %s: String { L(%s) }\n", name, call)
	default:
		fmt.Fprintf(b, "    static func %s(%s) -> String {\n", name, strings.Join(params, ", "))
		fmt.Fprintf(b, "        L(%s, %s)\n    }\n", call, strings.Join(plain, ", "))
	}
	return nil
}

// appleDoc writes an accessor's doc comment: the English text (each form
// of a plural) and the note.
func appleDoc(b *strings.Builder, e *model.Entry) {
	var lines []string
	if e.Text.Plural {
		lines = append(lines, strings.Split("one: "+e.Text.One, "\n")...)
		lines = append(lines, strings.Split("other: "+e.Text.Other, "\n")...)
	} else {
		lines = append(lines, strings.Split(e.Text.Other, "\n")...)
	}
	lines = append(lines, "")
	lines = append(lines, strings.Split(e.Note, "\n")...)
	for _, l := range lines {
		l = strings.TrimRightFunc(appleCommentSafe(l), unicode.IsSpace)
		if l == "" {
			b.WriteString("    ///\n")
		} else {
			b.WriteString("    /// " + l + "\n")
		}
	}
}

// appleCommentSafe replaces what could end a comment line or change how
// it reads: control characters, line and paragraph separators, bidi
// controls and other invisible format characters.
func appleCommentSafe(s string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case unicode.IsControl(r):
			return ' '
		case r == 0x2028 || r == 0x2029 || unicode.Is(unicode.Cf, r):
			return '�'
		}
		return r
	}, s)
}

// swiftQuote writes s as a Swift string literal: backslashes and quotes
// escaped (so no interpolation), and anything not visibly printable -
// controls, bidi and format characters, unusual spaces - as \u{...}.
func swiftQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"':
			b.WriteString(`\"`)
		case r == '\\':
			b.WriteString(`\\`)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\t':
			b.WriteString(`\t`)
		case r == '\r':
			b.WriteString(`\r`)
		case unicode.IsPrint(r) && !unicode.Is(unicode.Cf, r):
			b.WriteRune(r)
		default:
			fmt.Fprintf(&b, `\u{%X}`, r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// appleLanguages writes Languages.swift: the languages of this build, as
// L10n reads them.
func appleLanguages(opts Options) []byte {
	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-or-later\n//\n")
	fmt.Fprintf(&b, "// Code generated by i18ngen from %s. DO NOT EDIT.\n", model.LanguagesFile)
	b.WriteString("// It lists the shipping languages; make i18n DRAFT=1 adds the drafts and the pseudo-locale.\n")
	if opts.Draft {
		b.WriteString(appleDraftLine)
	}
	b.WriteString(`
/// A language this build of the app can show its own text in.
struct L10nLanguage: Sendable, Hashable, Identifiable {
    /// The code stored on the device and sent in every request ("pt").
    let code: String
    /// The BCP 47 tag that picks plural rules and number formats ("pt-PT").
    let tag: String
    /// The .lproj folder its compiled tables are in ("pt-PT").
    let apple: String
    /// The language's own name, for the picker ("Português").
    let name: String
    /// The pseudo-locale of draft builds, never matched to the system language.
    let pseudo: Bool

    var id: String { code }
}

extension L10nLanguage {
    /// Every language of this build, in the picker's order, English first.
    static let all: [L10nLanguage] = [
`)
	for _, l := range opts.Languages {
		fmt.Fprintf(&b, "        L10nLanguage(code: %s, tag: %s, apple: %s, name: %s, pseudo: %t),\n",
			swiftQuote(l.Code), swiftQuote(l.Tag), swiftQuote(l.Apple), swiftQuote(l.Name), l.Pseudo)
	}
	b.WriteString(`    ]

    /// English: the source text, and the fallback for anything missing.
    static let english = all[0]
}
`)
	return []byte(b.String())
}
