// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/alonsovidales/otc/i18n/model"
)

func init() { register(wizardEmitter{}) }

// wizardEmitter writes the setup wizard's text into scripts/setup_wizard.py
// (stdlib-only Python, one file in the image), between two marker lines:
//
//	# BEGIN GENERATED I18N
//	I18N = {"en": {"common.cancel": "Cancel", ...}, ...}
//	# END GENERATED I18N
//
// I18N is one JSON literal - language code -> key -> text, a text being a
// string or {"one": ..., "other": ...} - which Python reads as the same
// dict. English has every key; another language only its current
// translations, so that the wizard falls back to I18N["en"] key by key and
// picks the plural form of an English text by English rules (as package
// i18n does). encoding/json writes only strings, objects and the escapes
// both languages share (\" \\ \n \uXXXX ...; never \/, and characters
// outside the BMP as they are, never as surrogate pairs Python wouldn't
// join). The rest of the file is the wizard's own, kept byte for byte; the
// file is edited in part, so it isn't in Owns.
type wizardEmitter struct{}

func (wizardEmitter) Name() string        { return "wizard" }
func (wizardEmitter) Consumers() []string { return []string{model.ConsumerWizard} }
func (wizardEmitter) Owns() []string      { return nil }

const (
	wizardFile  = "scripts/setup_wizard.py"
	wizardBegin = "# BEGIN GENERATED I18N"
	wizardEnd   = "# END GENERATED I18N"
)

func (wizardEmitter) Emit(c *model.Catalog, opts Options) (map[string][]byte, error) {
	src, err := os.ReadFile(filepath.Join(opts.Root, filepath.FromSlash(wizardFile)))
	if errors.Is(err, fs.ErrNotExist) {
		// A repository without the wizard (a test's) has nothing to edit.
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	block, err := wizardBlock(c, opts)
	if err != nil {
		return nil, err
	}
	out, err := wizardReplace(src, block)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{wizardFile: out}, nil
}

// wizardBlock is what goes between the markers.
func wizardBlock(c *model.Catalog, opts Options) ([]byte, error) {
	dict := map[string]map[string]any{}
	for _, l := range opts.Languages {
		if !goCodePattern.MatchString(l.Code) {
			return nil, fmt.Errorf("language code %q", l.Code)
		}
		texts := map[string]any{}
		for _, e := range c.EntriesFor(model.ConsumerWizard) {
			if !model.KeyPattern.MatchString(e.Key) {
				return nil, fmt.Errorf("%q is not a key", e.Key)
			}
			r, _ := c.Resolve(l, e.Key)
			if !l.IsSource() && (r.Fallback() || r.State == model.StateSource) {
				continue // English, from I18N["en"]
			}
			if r.Text.Plural != e.Text.Plural {
				return nil, fmt.Errorf("%s: the %s text and the English differ in plural forms", e.Key, l.Code)
			}
			if err := checkGoForms(e, r.Text); err != nil {
				return nil, fmt.Errorf("%s (%s)", err, l.Code)
			}
			if r.Text.Plural {
				texts[e.Key] = map[string]string{model.FormOne: r.Text.One, model.FormOther: r.Text.Other}
			} else {
				texts[e.Key] = r.Text.Other
			}
		}
		dict[l.Code] = texts
	}
	// encoding/json's default HTML escaping keeps <, > and & out of the
	// literal too, should the wizard ever write a text into its page.
	lit, err := json.MarshalIndent(dict, "", "    ")
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("# Generated by make i18n (i18n/cmd/i18ngen) from i18n/strings, prefixes\n")
	b.WriteString("# common and wiz: do not edit. Language code -> key -> text, a text being\n")
	b.WriteString("# a string or a plural's {\"one\": ..., \"other\": ...}; shipping languages.\n")
	b.WriteString("# English has every key, the others their translations: fall back to \"en\".\n")
	if opts.Draft {
		b.WriteString("# " + DraftMarker + ": make i18n DRAFT=1 output, never commit it.\n")
	}
	b.WriteString("I18N = ")
	b.Write(lit)
	b.WriteString("\n")
	return b.Bytes(), nil
}

// wizardReplace puts block between the marker lines of src: each must be a
// whole line, there exactly once, BEGIN before END.
func wizardReplace(src, block []byte) ([]byte, error) {
	lines := strings.SplitAfter(string(src), "\n")
	begin, end := -1, -1
	for i, l := range lines {
		switch strings.TrimRight(l, "\r\n") {
		case wizardBegin:
			if begin >= 0 {
				return nil, fmt.Errorf("%s: %q appears twice", wizardFile, wizardBegin)
			}
			begin = i
		case wizardEnd:
			if end >= 0 {
				return nil, fmt.Errorf("%s: %q appears twice", wizardFile, wizardEnd)
			}
			end = i
		}
	}
	if begin < 0 || end < begin {
		return nil, fmt.Errorf("%s needs the lines %q and then %q around the generated text", wizardFile, wizardBegin, wizardEnd)
	}
	var b bytes.Buffer
	for _, l := range lines[:begin+1] {
		b.WriteString(l)
	}
	b.Write(block)
	for _, l := range lines[end:] {
		b.WriteString(l)
	}
	return b.Bytes(), nil
}
