// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"fmt"
	"slices"
	"sort"
	"strings"
	"unicode"

	"github.com/alonsovidales/otc/i18n/model"
)

// The Kotlin half of the Android emitter (emit_android_res.go): the
// accessors and the language table.

// androidAccessorFile writes S_<Prefix>.kt: the accessors of one prefix.
func androidAccessorFile(c *model.Catalog, prefix string, draft bool) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
	fmt.Fprintf(&b, "// Code generated by i18ngen from %s/%s/%s.json. DO NOT EDIT.\n", model.StringsDir, model.SourceCode, prefix)
	b.WriteString("// Change the catalog and run make i18n (i18n/README.md).\n")
	if draft {
		b.WriteString("// " + DraftMarker + "\n")
	}
	fmt.Fprintf(&b, "\npackage %s\n\nimport %s\n", androidPackage, androidRClass)
	for _, e := range c.EntriesIn(prefix) {
		if !c.Serves(model.ConsumerAndroid, e.Root) {
			continue
		}
		code, err := androidAccessor(e)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", e.Key, err)
		}
		b.WriteString("\n")
		b.WriteString(code)
	}
	return []byte(b.String()), nil
}

// androidAccessor writes one key's accessor:
//
//	/** "{name} deleted {count} photos" (one: "{name} deleted a photo"): Alert line. */
//	fun S.appPhotosDeletedBy(name: String, count: Int): UiText =
//	    UiText.Plural(R.plurals.app_photos_deleted_by, count, listOf(name, count))
func androidAccessor(e *model.Entry) (string, error) {
	var params, args []string
	for _, a := range e.Args {
		t, err := androidKotlinType(a.Type)
		if err != nil {
			return "", err
		}
		id := model.ArgName(a.Name)
		params = append(params, id+": "+t)
		args = append(args, id)
	}
	kind, res := "UiText", "R.string."
	if e.IsRich() {
		kind = "RichText"
	}
	if e.Text.Plural {
		res = "R.plurals."
	}
	call := []string{res + model.AndroidName(e.Key)}
	ctor := kind + ".Res"
	if e.Text.Plural {
		cnt, _, _ := e.CountArg()
		ctor = kind + ".Plural"
		call = append(call, model.ArgName(cnt.Name))
	}
	if len(args) > 0 {
		call = append(call, "listOf("+strings.Join(args, ", ")+")")
	}

	var b strings.Builder
	b.WriteString("/** ")
	if e.Text.Plural {
		fmt.Fprintf(&b, "%s (one: %s)", androidDocQuote(e.Text.Other), androidDocQuote(e.Text.One))
	} else {
		b.WriteString(androidDocQuote(e.Text.Other))
	}
	if e.Note != "" {
		b.WriteString(": " + androidDocText(e.Note))
	}
	if e.IsRich() {
		tags := slices.Clone(e.Rich)
		sort.Strings(tags)
		fmt.Fprintf(&b, " Tags: %s.", androidDocText(strings.Join(tags, ", ")))
	}
	if !e.Translate {
		b.WriteString(" Never translated.")
	}
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "fun S.%s(%s): %s =\n    %s(%s)\n", model.CamelName(e.Key), strings.Join(params, ", "), kind, ctor, strings.Join(call, ", "))
	return b.String(), nil
}

// androidDocQuote is a text quoted for a KDoc comment.
func androidDocQuote(s string) string { return `"` + androidDocText(s) + `"` }

// androidDocText makes text safe inside a one-line /** ... */ comment:
// nothing that closes or (Kotlin nests them) opens a comment, no line
// break, and no invisible or bidi character that could make the source
// read differently from what compiles.
func androidDocText(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '\n':
			b.WriteString(`\n`)
		case !unicode.IsPrint(r) || unicode.Is(unicode.Cf, r):
			fmt.Fprintf(&b, `\u%04X`, r)
		default:
			b.WriteRune(r)
		}
	}
	out := b.String()
	for strings.Contains(out, "*/") || strings.Contains(out, "/*") {
		out = strings.ReplaceAll(strings.ReplaceAll(out, "*/", "* /"), "/*", "/ *")
	}
	return out
}

// androidKotlinString is a Kotlin string literal.
func androidKotlinString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '\\' || r == '"' || r == '$':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r == '\n':
			b.WriteString(`\n`)
		case r < 0x10000 && (!unicode.IsPrint(r) || unicode.Is(unicode.Cf, r)):
			fmt.Fprintf(&b, `\u%04X`, r)
		case !unicode.IsPrint(r) || unicode.Is(unicode.Cf, r):
			// Kotlin has no \U: a surrogate pair.
			r1, r2 := androidUTF16Pair(r)
			fmt.Fprintf(&b, `\u%04X\u%04X`, r1, r2)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// androidUTF16Pair splits a supplementary code point into its surrogates.
func androidUTF16Pair(r rune) (rune, rune) {
	r -= 0x10000
	return 0xd800 + (r>>10)&0x3ff, 0xdc00 + r&0x3ff
}

// androidLanguagesFile writes Languages.kt.
func androidLanguagesFile(langs []model.Language, draft bool) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// SPDX-License-Identifier: AGPL-3.0-or-later\n")
	b.WriteString("// Code generated by i18ngen from i18n/languages.json. DO NOT EDIT.\n")
	b.WriteString("// Change the catalog and run make i18n (i18n/README.md).\n")
	if draft {
		b.WriteString("// " + DraftMarker + "\n")
	}
	fmt.Fprintf(&b, "\npackage %s\n", androidPackage)
	b.WriteString(`
/** A language the app's generated resources hold (i18n/languages.json). */
data class Language(
    /** Stored, sent on the wire and used in file names ("pt"). */
    val code: String,
    /**
     * The BCP 47 tag behind plural rules and number formats ("pt-PT"), and the
     * locale to hand Android (setApplicationLocales or a configuration):
     * values-<qualifier> holds its resources. Always this tag, never the bare
     * code: "pt" would pick Brazilian plural rules from the same values-pt.
     */
    val tag: String,
    /** The language's own name, for the picker. */
    val name: String,
)

/**
 * The languages of this build, English first: the shipping ones, and in a
 * make i18n DRAFT=1 build (never committed) the drafts and the pseudo-locale.
 */
object Languages {
    /** English: the source, and the text of anything not translated. */
    const val SOURCE: String = "en"

    val all: List<Language> = listOf(
`)
	for _, l := range langs {
		if !androidCodePattern.MatchString(l.Code) {
			return nil, fmt.Errorf("language code %q is not valid", l.Code)
		}
		tag := androidTag(l)
		if !androidTagPattern.MatchString(tag) {
			return nil, fmt.Errorf("%s: tag %q is not valid", l.Code, tag)
		}
		fmt.Fprintf(&b, "        Language(code = %s, tag = %s, name = %s),\n", androidKotlinString(l.Code), androidKotlinString(tag), androidKotlinString(l.Name))
	}
	b.WriteString(`    )

    /** The language with this code, or null. */
    fun forCode(code: String): Language? = all.firstOrNull { it.code == code }
}
`)
	return []byte(b.String()), nil
}

// androidLocalesFile writes locales_config.xml.
func androidLocalesFile(langs []model.Language, draft bool) ([]byte, error) {
	var b strings.Builder
	b.WriteString("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
	b.WriteString("<!-- Generated by i18ngen from i18n/languages.json: do not edit, run make i18n (i18n/README.md).\n")
	b.WriteString("     The languages the app's resources hold, for android:localeConfig. -->\n")
	if draft {
		b.WriteString("<!-- " + DraftMarker + " -->\n")
	}
	b.WriteString("<locale-config xmlns:android=\"http://schemas.android.com/apk/res/android\">\n")
	for _, l := range langs {
		tag := androidTag(l)
		if !androidTagPattern.MatchString(tag) {
			return nil, fmt.Errorf("%s: tag %q is not valid", l.Code, tag)
		}
		fmt.Fprintf(&b, "    <locale android:name=\"%s\" />\n", tag)
	}
	b.WriteString("</locale-config>\n")
	return []byte(b.String()), nil
}
